theme: jekyll-theme-slate

email: bahnson@hotmail.de
title: bahnson @ GitHub
description: >- # this means to ignore newlines until "baseurl:"
  GitHub page of Christopher Bahn.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bahnson
twitter_username: bahnbird

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

# front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"